// 20 ultra high-quality viral video templates inspired by top social media trends.
// Each template targets ages 12-40 and produces cinematic vertical (9:16) videos.

export const VIRAL_TEMPLATES = [
  {
    id: "cinematic-drone-reveal",
    name: "Cinematic Drone Reveal",
    category: "Travel",
    tagline: "Sweeping aerial shots that end on a breathtaking vista",
    description: "Golden-hour drone footage revealing landscapes from above. The ultimate travel flex — starts low, climbs high, ends on a jaw-dropping panorama.",
    hook_pattern: "Start 2m off the ground, climb to 50m in 3 seconds revealing the full scene",
    pacing: "Slow build, one continuous shot, 6-8 seconds",
    shot_list: ["Low altitude ground-level start", "Ascending climb revealing scale", "High-altitude panorama finish"],
    music_style: "Epic orchestral swell or ambient cinematic pad",
    caption_formula: "POV: you found the best view in [location] 📍",
    visual_effects: ["Golden hour color grade", "Smooth gimbal stabilization", "Lens flare on ascent"],
    color_palette: ["#FF8C42", "#FFD700", "#1E3A5F", "#0A0A0A"],
    font_style: "Clean sans-serif, lowercase, centered bottom-third",
    thumbnail_text_pattern: "Location name in small elegant text, bottom center",
    best_for: ["Travel", "Real estate", "Adventure", "Nature"],
    difficulty: "intermediate",
    avg_duration: 8,
    aspect_ratio: "9:16",
    lighting_style: "Golden hour natural light",
    transition_style: "Continuous single take",
    symbols_motifs: ["Mountains", "Ocean", "City skyline"],
    preview: { gradient: "linear-gradient(to top, #1E3A5F 0%, #FF8C42 60%, #FFD700 100%)", icon: "🏔️", hookText: "POV: best view", textPos: "bottom" },
  },
  {
    id: "pov-first-person",
    name: "POV First Person",
    category: "Lifestyle",
    tagline: "Your hands. Your world. Total immersion.",
    description: "First-person perspective that puts the viewer in your shoes. The most addictive format on TikTok — viewers feel like they're doing it with you.",
    hook_pattern: "Hands enter frame doing something satisfying in the first second",
    pacing: "Medium cuts every 1-2 seconds, rhythmic",
    shot_list: ["Hands reaching for object", "Action in progress", "Satisfying result reveal"],
    music_style: "Lo-fi beat or trending TikTok sound",
    caption_formula: "POV: it's 3am and you're [relatable action]",
    visual_effects: ["Hand-held natural shake", "Shallow depth of field", "Warm color grade"],
    color_palette: ["#2D1B69", "#FF6B9D", "#FFE66D", "#1A1A2E"],
    font_style: "Bold rounded sans-serif, white with subtle shadow, top-center",
    thumbnail_text_pattern: "POV text in bold white, top center, 3 lines max",
    best_for: ["Cooking", "Crafting", "Morning routines", "ASMR"],
    difficulty: "beginner",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Soft natural window light",
    transition_style: "Whip pan or hard cut on beat",
    symbols_motifs: ["Hands", "Everyday objects", "Steam", "Textures"],
    preview: { gradient: "linear-gradient(135deg, #2D1B69 0%, #FF6B9D 100%)", icon: "✋", hookText: "POV: 3am vibes", textPos: "top" },
  },
  {
    id: "speed-ramp-transition",
    name: "Speed Ramp Transition",
    category: "Sports",
    tagline: "Ultra-fast cuts that hit on every beat drop",
    description: "Speed ramping between slow-motion and hyper-fast clips synced to a beat drop. The most energy-dense format — every frame matters.",
    hook_pattern: "Slow-motion start, speed ramps into a blur, hard cut on the drop",
    pacing: "Variable speed: slow → fast → freeze → fast",
    shot_list: ["Slow-mo wind-up", "Speed ramp into action", "Freeze frame on peak moment", "Fast cut to result"],
    music_style: "EDM beat drop or phonk with heavy bass",
    caption_formula: "Wait for it… 🎧",
    visual_effects: ["Speed ramp (optical flow)", "Motion blur on fast sections", "Flash frame on beat drop"],
    color_palette: ["#FF006E", "#3A86FF", "#FFBE0B", "#0A0A0A"],
    font_style: "Impact-style bold uppercase, neon glow, center screen",
    thumbnail_text_pattern: "Single bold word center screen with glow effect",
    best_for: ["Sports", "Dance", "Fitness", "Action"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "High-contrast dramatic lighting",
    transition_style: "Speed ramp blur into hard cut",
    symbols_motifs: ["Motion lines", "Freeze frame", "Beat sync"],
    preview: { gradient: "linear-gradient(to bottom, #FF006E, #3A86FF)", icon: "⚡", hookText: "Wait for it…", textPos: "center" },
  },
  {
    id: "golden-hour-portrait",
    name: "Golden Hour Portrait",
    category: "Fashion",
    tagline: "Backlit beauty that makes anyone look cinematic",
    description: "Warm backlight, shallow depth of field, and natural lens flare. The most flattering lighting setup — turns any moment into a movie poster.",
    hook_pattern: "Subject turns into the light, hair catches the sun, soft smile",
    pacing: "Slow, contemplative, 2-3 shots maximum",
    shot_list: ["Backlit silhouette", "Turn into light catching hair", "Soft portrait with flare"],
    music_style: "Dreamy indie folk or slowed R&B",
    caption_formula: "golden hour hits different ✨",
    visual_effects: ["Natural lens flare", "Warm orange/teal color grade", "Bokeh background"],
    color_palette: ["#FFB347", "#FF6B35", "#2C1810", "#F5E6D3"],
    font_style: "Elegant serif italic, warm white, bottom-left small",
    thumbnail_text_pattern: "Minimal text, warm tones, subject centered",
    best_for: ["Fashion", "Beauty", "Portraits", "Lifestyle"],
    difficulty: "beginner",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Golden hour backlight (1 hour before sunset)",
    transition_style: "Soft dissolve or no cuts",
    symbols_motifs: ["Sun flare", "Hair glow", "Warm tones"],
    preview: { gradient: "linear-gradient(to top, #2C1810, #FF6B35, #FFB347)", icon: "🌅", hookText: "golden hour ✨", textPos: "bottom" },
  },
  {
    id: "neon-night-walk",
    name: "Neon Night Walk",
    category: "Urban",
    tagline: "City lights, moody vibes, main character energy",
    description: "Neon-lit night streets with reflective surfaces and cyberpunk color grading. The aesthetic that defines Gen Z nightlife content.",
    hook_pattern: "Subject walks toward camera under neon signs, reflections in puddles",
    pacing: "Medium, walk-paced, 3-4 cuts over 6 seconds",
    shot_list: ["Wide neon street approach", "Reflection in puddle/glass", "Close-up under neon sign", "Look back at camera"],
    music_style: "Synthwave, dark R&B, or slowed + reverb",
    caption_formula: "night walks just hit different 🌃",
    visual_effects: ["Neon color grade (magenta/cyan)", "Reflection compositing", "Slight grain and halation"],
    color_palette: ["#FF00FF", "#00FFFF", "#1A0033", "#0A0A0A"],
    font_style: "Neon glow sans-serif, magenta or cyan, center screen",
    thumbnail_text_pattern: "Neon text overlay, subject in lower third",
    best_for: ["Street fashion", "Night life", "Urban exploration", "Music"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Neon street lights, practicals only",
    transition_style: "Match cut on walking motion",
    symbols_motifs: ["Neon signs", "Reflections", "Rain", "City lights"],
    preview: { gradient: "linear-gradient(to bottom, #1A0033, #FF00FF 50%, #00FFFF)", icon: "🌃", hookText: "night walks 🌃", textPos: "center" },
  },
  {
    id: "transformation-reveal",
    name: "Before / After Transformation",
    category: "Beauty",
    tagline: "The snap that keeps viewers watching to the end",
    description: "Show the 'before', snap transition, reveal the 'after'. The highest-retention format on social media — viewers MUST see the result.",
    hook_pattern: "Plain/unstyled subject snaps fingers → full transformation",
    pacing: "Two shots: 2s before, snap, 4s after reveal",
    shot_list: ["Before state (plain)", "Snap/cover transition", "After reveal (full glam/look)", "Confidence walk or pose"],
    music_style: "Beat drop on the reveal moment",
    caption_formula: "the glow up 💅",
    visual_effects: ["Snap transition (hand cover or whip)", "Color grade shift before→after", "Confidence boost lighting"],
    color_palette: ["#E63946", "#F1FAEE", "#A8DADC", "#1D3557"],
    font_style: "Bold uppercase, white, centered on reveal",
    thumbnail_text_pattern: "Split: before left, after right, arrow between",
    best_for: ["Makeup", "Fashion", "Fitness", "Room decor"],
    difficulty: "beginner",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Flat even light before, dramatic after",
    transition_style: "Snap/whip/cover transition",
    symbols_motifs: ["Snap", "Arrow", "Sparkle", "Glow"],
    preview: { gradient: "linear-gradient(135deg, #1D3557 0%, #E63946 100%)", icon: "✨", hookText: "the glow up 💅", textPos: "center" },
  },
  {
    id: "stop-motion-magic",
    name: "Stop Motion Magic",
    category: "Creative",
    tagline: "Objects that move on their own — pure delight",
    description: "Frame-by-frame animation where objects appear to move themselves. The most satisfying format to watch — impossible to scroll past.",
    hook_pattern: "Object slides into frame on its own in the first second",
    pacing: "12-15fps choppy, each frame is a beat",
    shot_list: ["Object enters frame", "Objects interact/move", "Final arrangement forms a word or shape"],
    music_style: "Playful plucks or music box melody",
    caption_formula: "it made itself 🤷",
    visual_effects: ["Stop motion (12fps)", "Tripod-locked camera", "Consistent lighting"],
    color_palette: ["#FF6B9D", "#C7F0DB", "#FFD93D", "#6BCB77"],
    font_style: "Playful rounded font, pastel colors, bouncing animation",
    thumbnail_text_pattern: "Objects arranged to spell the hook text",
    best_for: ["Product showcase", "Art", "Food styling", "Crafts"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Flat even daylight, no shadows",
    transition_style: "No transitions — every frame is a cut",
    symbols_motifs: ["Floating objects", "Self-arranging", "Playful chaos"],
    preview: { gradient: "linear-gradient(to top, #C7F0DB, #FF6B9D)", icon: "🎨", hookText: "it made itself 🤷", textPos: "center" },
  },
  {
    id: "split-screen-story",
    name: "Split Screen Story",
    category: "Storytelling",
    tagline: "Two perspectives. One story. Double the watch time.",
    description: "Two vertical clips side by side telling parallel or contrasting stories. Doubles retention — viewers watch twice to catch both sides.",
    hook_pattern: "Two contrasting scenes side by side from frame one",
    pacing: "Synchronized cuts, both sides change together",
    shot_list: ["Split: expectation vs reality", "Split: two people's POV", "Split merges into full screen"],
    music_style: "Same track both sides, or contrasting genres",
    caption_formula: "me vs my friend / expectation vs reality",
    visual_effects: ["Center divider line", "Synchronized timing", "Optional merge at end"],
    color_palette: ["#6366F1", "#EC4899", "#1E293B", "#F1F5F9"],
    font_style: "Labels above each side, bold uppercase",
    thumbnail_text_pattern: "Two labels: 'ME' left, 'THEM' right",
    best_for: ["Comedy", "Comparison", "Couples", "Before/after"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Matched lighting on both sides",
    transition_style: "Hard cuts synced across both sides",
    symbols_motifs: ["Divider line", "VS", "Mirror"],
    preview: { gradient: "linear-gradient(to right, #6366F1 50%, #EC4899 50%)", icon: "📐", hookText: "me vs them", textPos: "top" },
  },
  {
    id: "whip-pan-journey",
    name: "Whip Pan Journey",
    category: "Travel",
    tagline: "One seamless journey through multiple locations",
    description: "Whip-pan transitions connect different locations into one continuous journey. Makes viewers feel like they teleported — insanely engaging.",
    hook_pattern: "Whip pan right → new location, whip pan right → another location",
    pacing: "Fast, 1-2 seconds per location, whip between each",
    shot_list: ["Location 1 (whip out)", "Location 2 (whip in/out)", "Location 3 (whip in/out)", "Location 4 (whip in, hold)"],
    music_style: "Upbeat travel indie or afrobeat",
    caption_formula: "3 countries in 6 seconds 🌍",
    visual_effects: ["Whip pan transitions (motion blur)", "Match speed on whip in/out", "Consistent framing across locations"],
    color_palette: ["#F97316", "#06B6D4", "#8B5CF6", "#FBBF24"],
    font_style: "Location labels appearing on each whip-in, bold sans",
    thumbnail_text_pattern: "Location count: '3 places' bold center",
    best_for: ["Travel", "Food tour", "City guides", "Events"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Natural daylight, consistent across locations",
    transition_style: "Whip pan (fast horizontal camera swing)",
    symbols_motifs: ["Motion blur", "Passports", "Maps"],
    preview: { gradient: "linear-gradient(to right, #F97316, #06B6D4, #8B5CF6)", icon: "🌍", hookText: "3 countries 🌍", textPos: "center" },
  },
  {
    id: "slow-motion-splash",
    name: "Slow Motion Splash",
    category: "Food",
    tagline: "120fps liquid physics that's impossible to scroll past",
    description: "Ultra slow-motion capture of water, sauce, or particles in motion. The most visually mesmerizing format — pure eye candy.",
    hook_pattern: "Liquid/particle suspended mid-air in the first frame",
    pacing: "One continuous slow-motion shot, 6 seconds real-time = 1 second footage",
    shot_list: ["Pre-splash anticipation", "Splash moment at 120fps", "Settle and aftermath"],
    music_style: "Bass-heavy slowed beat or ASMR audio",
    caption_formula: "this took 47 takes 💦",
    visual_effects: ["120fps slow motion", "Backlight to catch particles", "Color-rich liquid"],
    color_palette: ["#EF4444", "#F59E0B", "#3B82F6", "#0C0A09"],
    font_style: "Minimal, small text bottom-center, white",
    thumbnail_text_pattern: "Splash frozen mid-frame, minimal text",
    best_for: ["Food", "Drinks", "Product", "Nature"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Strong backlight to illuminate particles",
    transition_style: "No cuts — single slow-motion take",
    symbols_motifs: ["Droplets", "Splash", "Pour", "Drip"],
    preview: { gradient: "linear-gradient(to bottom, #3B82F6, #0C0A09)", icon: "💦", hookText: "47 takes 💦", textPos: "bottom" },
  },
  {
    id: "glitch-transition",
    name: "Glitch Transition",
    category: "Tech",
    tagline: "Digital distortion that screams 'next level edit'",
    description: "RGB-split glitch transitions between scenes with datamosh and chromatic aberration. The signature look of tech and gaming content.",
    hook_pattern: "Digital glitch distortion tears the frame apart, reveals new scene",
    pacing: "Glitch transitions every 1.5 seconds, 3-4 scenes",
    shot_list: ["Scene 1 → glitch tear", "Scene 2 → glitch tear", "Scene 3 → glitch tear", "Scene 4 → hold"],
    music_style: "Glitch hop, industrial, or hyperpop",
    caption_formula: "system update complete ⚡",
    visual_effects: ["RGB channel split", "Datamosh distortion", "Scan lines and pixel sort"],
    color_palette: ["#00FF00", "#FF00FF", "#00FFFF", "#0A0A0A"],
    font_style: "Monospace terminal font, green or magenta, top-left",
    thumbnail_text_pattern: "Glitched text, partially corrupted, top-center",
    best_for: ["Gaming", "Tech", "Cyberpunk", "Music"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Neon and screen light, high contrast",
    transition_style: "Glitch/datamosh with RGB split",
    symbols_motifs: ["Scan lines", "Pixelation", "Error codes"],
    preview: { gradient: "linear-gradient(135deg, #00FF00 0%, #FF00FF 50%, #00FFFF 100%)", icon: "⚡", hookText: "system update ⚡", textPos: "top" },
  },
  {
    id: "text-driven-story",
    name: "Text-Driven Story",
    category: "Storytelling",
    tagline: "Kinetic typography that tells a story word by word",
    description: "Bold animated text appears over footage, each word hitting on a beat. The most readable and shareable format — viewers read along involuntarily.",
    hook_pattern: "First word appears huge and bold, fills the screen",
    pacing: "One word per beat, 6-8 words total",
    shot_list: ["Word 1 (full screen)", "Word 2 (shifts position)", "Footage with text overlay", "Final phrase complete"],
    music_style: "Beat with clear accents for text timing",
    caption_formula: "Story told entirely through on-screen text",
    visual_effects: ["Kinetic typography", "Text scale/position animation", "High contrast text on footage"],
    color_palette: ["#FFFFFF", "#000000", "#FFD700", "#FF006E"],
    font_style: "Ultra-bold display font, white with black outline, animated",
    thumbnail_text_pattern: "First word fills 60% of frame, bold uppercase",
    best_for: ["Motivation", "Storytime", "Education", "Quotes"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Any — text carries the story",
    transition_style: "Text animation between words",
    symbols_motifs: ["Typography", "Bold words", "Beat sync"],
    preview: { gradient: "linear-gradient(to bottom, #000000, #1a1a1a)", icon: "📝", hookText: "READ THIS", textPos: "center" },
  },
  {
    id: "mirror-reflection",
    name: "Mirror Reflection",
    category: "Creative",
    tagline: "Symmetrical compositions that stop the scroll",
    description: "Creative use of mirrors, water reflections, and symmetry. The most visually striking composition technique — viewers pause to figure it out.",
    hook_pattern: "Subject looks in mirror, but the reflection does something different",
    pacing: "Slow, 2-3 shots, contemplative",
    shot_list: ["Subject approaches mirror", "Reflection reveals twist", "Pull back to show full scene"],
    music_style: "Eerie ambient or reversed audio",
    caption_formula: "which one is real? 🪞",
    visual_effects: ["Mirror compositing", "Perfect symmetry", "Reflection mismatch (creative twist)"],
    color_palette: ["#7C3AED", "#1E1B4B", "#C4B5FD", "#0A0A0A"],
    font_style: "Thin elegant serif, centered, low opacity",
    thumbnail_text_pattern: "Question text, small, center, mysterious",
    best_for: ["Fashion", "Art", "Conceptual", "Music videos"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Dramatic single-source, symmetrical",
    transition_style: "Mirror wipe or slow dissolve",
    symbols_motifs: ["Mirror", "Water", "Symmetry", "Doppelgänger"],
    preview: { gradient: "linear-gradient(to bottom, #1E1B4B, #7C3AED)", icon: "🪞", hookText: "which is real? 🪞", textPos: "center" },
  },
  {
    id: "timelapse-city",
    name: "Time Lapse City",
    category: "Urban",
    tagline: "Hours compressed into seconds — the city comes alive",
    description: "Hyper-lapse through a city with light trails and cloud movement. Shows the energy of a place in a way no real-time shot can.",
    hook_pattern: "Static frame, time accelerates, city lights start moving",
    pacing: "One continuous timelapse, 6 seconds = 2 hours",
    shot_list: ["Daytime establishing shot", "Sunset transition (accelerated)", "Night with light trails"],
    music_style: "Building electronic or cinematic crescendo",
    caption_formula: "this city never sleeps 🌃",
    visual_effects: ["Time lapse (interval shooting)", "Light trail long exposure", "Cloud motion blur"],
    color_palette: ["#1E40AF", "#F59E0B", "#7C3AED", "#0F172A"],
    font_style: "Bold condensed sans, white, bottom-center with city name",
    thumbnail_text_pattern: "City name bold, light trails visible",
    best_for: ["Travel", "Real estate", "Events", "City life"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Natural transitioning to artificial night",
    transition_style: "Time dissolve (day to night)",
    symbols_motifs: ["Light trails", "Moving clouds", "Traffic"],
    preview: { gradient: "linear-gradient(to top, #0F172A, #1E40AF, #F59E0B)", icon: "🏙️", hookText: "never sleeps 🌃", textPos: "bottom" },
  },
  {
    id: "macro-detail",
    name: "Macro Detail Close-Up",
    category: "Product",
    tagline: "Extreme close-ups that reveal hidden worlds",
    description: "Ultra-close macro shots of textures, details, and small objects. The most satisfying product showcase format — viewers see what eyes can't.",
    hook_pattern: "Start so close the viewer can't tell what it is, then slowly pull back",
    pacing: "Slow, 3-4 shots, each a different detail",
    shot_list: ["Extreme close-up (unrecognizable)", "Slight pull-back (context)", "Full product reveal"],
    music_style: "ASMR or ambient with subtle textures",
    caption_formula: "look closer 👀",
    visual_effects: ["Macro lens (1:1 or greater)", "Shallow depth of field", "Rack focus between details"],
    color_palette: ["#10B981", "#F3F4F6", "#6B7280", "#111827"],
    font_style: "Clean minimal sans, small, bottom-left, neutral",
    thumbnail_text_pattern: "Abstract texture fills frame, minimal text",
    best_for: ["Product", "Food", "Jewelry", "Crafts"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Soft diffused macro lighting",
    transition_style: "Rack focus (blur between details)",
    symbols_motifs: ["Texture", "Detail", "Close-up", "Reveal"],
    preview: { gradient: "radial-gradient(circle at center, #10B981, #111827)", icon: "🔍", hookText: "look closer 👀", textPos: "bottom" },
  },
  {
    id: "aerial-orbit",
    name: "Aerial Orbit",
    category: "Travel",
    tagline: "360° drone orbit that makes anything look epic",
    description: "Drone circles the subject in a perfect orbit, revealing the full environment. The signature shot of every viral travel and event video.",
    hook_pattern: "Drone starts behind subject, orbits to front revealing the vista",
    pacing: "One continuous orbit, 6 seconds, smooth",
    shot_list: ["Start behind subject", "Orbit 180° revealing landscape", "Complete orbit to front"],
    music_style: "Cinematic build or orchestral swell",
    caption_formula: "this spot is unreal 🤯",
    visual_effects: ["Drone orbit (perfect circle)", "Gimbal stabilization", "Cinematic color grade"],
    color_palette: ["#0EA5E9", "#FDE68A", "#65A30D", "#1E293B"],
    font_style: "Clean sans-serif, white, bottom-center, location tag",
    thumbnail_text_pattern: "Location name, small elegant text, bottom",
    best_for: ["Travel", "Events", "Weddings", "Real estate"],
    difficulty: "intermediate",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Golden hour or blue hour",
    transition_style: "Continuous orbit (no cuts)",
    symbols_motifs: ["Circle", "Panorama", "Height"],
    preview: { gradient: "conic-gradient(from 0deg, #0EA5E9, #FDE68A, #65A30D, #0EA5E9)", icon: "🚁", hookText: "this spot 🤯", textPos: "bottom" },
  },
  {
    id: "shadow-play",
    name: "Shadow Play",
    category: "Artistic",
    tagline: "Dramatic silhouettes that tell a story in darkness",
    description: "High-contrast lighting creating bold silhouettes and shadows. The most artistic and moody format — pure cinema in 6 seconds.",
    hook_pattern: "Subject in silhouette against a bright background, shadow stretches",
    pacing: "Slow, 2-3 shots, deliberate",
    shot_list: ["Silhouette against window/light", "Shadow interaction or movement", "Partial reveal into light"],
    music_style: "Dark ambient, noir jazz, or dramatic classical",
    caption_formula: "shadows know the truth 🖤",
    visual_effects: ["High contrast (crushed blacks)", "Single light source", "Silhouette compositing"],
    color_palette: ["#0A0A0A", "#F5F5F5", "#71717A", "#FBBF24"],
    font_style: "Thin elegant serif, white, centered, low opacity",
    thumbnail_text_pattern: "Minimal text, mostly shadow, single accent",
    best_for: ["Dance", "Fashion", "Art", "Music"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Single hard source (window, spotlight)",
    transition_style: "Shadow wipe or slow fade",
    symbols_motifs: ["Silhouette", "Shadow", "Light beam"],
    preview: { gradient: "linear-gradient(to bottom, #0A0A0A 70%, #FBBF24)", icon: "🖤", hookText: "shadows know 🖤", textPos: "center" },
  },
  {
    id: "color-pop",
    name: "Color Pop",
    category: "Creative",
    tagline: "Black and white world with one electric color",
    description: "Everything is desaturated except one vibrant color that pops. The most visually arresting effect — the eye locks onto the color instantly.",
    hook_pattern: "Black and white scene, then one object bursts into vivid color",
    pacing: "Medium, 3-4 shots, color reveals on each cut",
    shot_list: ["B&W establishing", "Color object enters (pops)", "Full scene with color accent", "Close-up of the color element"],
    music_style: "Minimalist piano or beat with a single accent hit",
    caption_formula: "she was the only color in his world 💔",
    visual_effects: ["Selective color (schindler's list effect)", "Crushed desaturated background", "Vivid color saturation on subject"],
    color_palette: ["#FF0000", "#808080", "#000000", "#FFFFFF"],
    font_style: "Bold condensed, white, minimal, bottom-center",
    thumbnail_text_pattern: "One colored object, rest B&W, minimal text",
    best_for: ["Fashion", "Product", "Art", "Storytelling"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Even flat lighting (color grade does the work)",
    transition_style: "Hard cut with color reveal",
    symbols_motifs: ["Single color", "Desaturation", "Contrast"],
    preview: { gradient: "linear-gradient(to bottom, #808080, #FF0000 50%, #808080)", icon: "🎨", hookText: "only color 💔", textPos: "center" },
  },
  {
    id: "invisible-cut",
    name: "Invisible Cut",
    category: "Storytelling",
    tagline: "Seamless match cuts that bend reality",
    description: "Match-on-action cuts where the viewer can't tell where one shot ends and another begins. Creates the illusion of one impossible continuous shot.",
    hook_pattern: "Subject performs an action, the cut happens mid-motion invisibly",
    pacing: "Appears as one shot, actually 3-4 matched cuts",
    shot_list: ["Action start (match out)", "Action continue (new location)", "Action complete (final location)"],
    music_style: "Continuous track, no beat drops (to preserve illusion)",
    caption_formula: "one take. zero cuts. 🎬",
    visual_effects: ["Match on action", "Same framing and motion across cuts", "Consistent color and lighting"],
    color_palette: ["#3B82F6", "#F59E0B", "#10B981", "#1E293B"],
    font_style: "Small subtle text, bottom-center, appears at end only",
    thumbnail_text_pattern: "Minimal, 'one take' text, bottom",
    best_for: ["Travel", "Lifestyle", "Product", "Creative"],
    difficulty: "advanced",
    avg_duration: 6,
    aspect_ratio: "9:16",
    lighting_style: "Matched lighting across all locations",
    transition_style: "Match cut on motion (invisible)",
    symbols_motifs: ["Motion", "Match", "Seamless"],
    preview: { gradient: "linear-gradient(135deg, #3B82F6, #10B981)", icon: "🎬", hookText: "one take 🎬", textPos: "bottom" },
  },
  {
    id: "epic-montage",
    name: "Epic Montage",
    category: "Cinematic",
    tagline: "Multiple scenes that build to one epic moment",
    description: "Rapid-fire montage of 4-6 scenes that build energy and culminate in a final epic shot. The format of every movie trailer — pure adrenaline.",
    hook_pattern: "Quick cuts building in speed, each shot shorter than the last",
    pacing: "Accelerating: 1.5s → 1s → 0.5s → 0.25s → hold on final",
    shot_list: ["Scene 1 (establishing)", "Scene 2 (building)", "Scene 3 (faster)", "Scene 4 (rapid)", "Final epic shot (hold 2s)"],
    music_style: "Building orchestral or EDM crescendo with a final drop",
    caption_formula: "this is what it's all about 🔥",
    visual_effects: ["Accelerating cut speed", "Building color saturation", "Flash to white on final shot"],
    color_palette: ["#FF6B00", "#FFD600", "#0047FF", "#0A0A0A"],
    font_style: "Bold uppercase, grows with each cut, final shot full-screen",
    thumbnail_text_pattern: "Final word fills screen, bold, with glow",
    best_for: ["Travel", "Sports", "Events", "Brand"],
    difficulty: "advanced",
    avg_duration: 8,
    aspect_ratio: "9:16",
    lighting_style: "Cinematic, escalating drama per shot",
    transition_style: "Accelerating hard cuts, flash on final",
    symbols_motifs: ["Fire", "Summit", "Crowd", "Peak moment"],
    preview: { gradient: "linear-gradient(to top, #0A0A0A, #0047FF, #FF6B00, #FFD600)", icon: "🔥", hookText: "THIS IS IT 🔥", textPos: "center" },
  },
];

export const VIRAL_CATEGORIES = [
  "All",
  "Travel",
  "Lifestyle",
  "Sports",
  "Fashion",
  "Urban",
  "Beauty",
  "Creative",
  "Storytelling",
  "Food",
  "Tech",
  "Product",
  "Artistic",
  "Cinematic",
];